dist: xenial
language: python
python: 3.7
install:
  - pip install pipenv
  - pipenv sync --dev
script:
  - black --check .
  - coverage run --source=drinks manage.py test
after_success:
  - coveralls

notifications:
  email: false
